version: "3.9"

services:
  automacao:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: automacao-python
    volumes:
      - ../logs:/app/logs
      - ../downloads:/app/downloads
    env_file:
      - ../.env
    environment:
      - ENVIRONMENT=docker
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data: